// vue-ethers/src/components/SendRbtc.vue
<script setup>
import { ref } from 'vue';
import { storeToRefs } from 'pinia';
import { utils } from 'ethers';
import { useRootstockStore } from '../stores/rootstock';

const rskStore = useRootstockStore();
const { errorMessage, loading, provider, balance } = storeToRefs(rskStore);

const rbtcToSend = ref(0.00001);
const toAddress = ref('0xB62BD53308fb2834b3114a5f725D0382CBe9f008');
const sendRbtc = async () => {
  try {
    errorMessage.value = '';
    loading.value = 'Initiating transaction';
    const signer = provider.value.getSigner(0);
    const tx = await signer.sendTransaction({
      to: utils.getAddress(toAddress.value),
      value: utils.parseEther(rbtcToSend.value.toString()),
    });
    loading.value = `Sending tx: ${tx.hash}`;
    await tx.wait();
  } catch (error) {
    if (error.code !== 'ACTION_REJECTED') errorMessage.value = error.message;
  } finally {
    loading.value = '';
  }
};
</script>

<template>
  <label>
    Send
    <input
      type="number"
      v-model="rbtcToSend"
      min="0"
      :max="balance"
      step="0.00001"
    />
    RBTC
  </label>
  <label>
    To address
    <input type="text" v-model="toAddress" />
  </label>
  <button @click="sendRbtc">send RBTC</button>
</template>

<style scoped>
button {
  cursor: pointer;
}
label {
  display: block;
}
input[type='number'] {
  width: 5rem;
}
input[type='text'] {
  width: 20rem;
}
</style>

// usedapp-rootstock/src/components/SendRbtc.jsx
import { useState } from 'react';
import { utils } from 'ethers';
import { useSendTransaction } from '@usedapp/core';

const faucetAddress = '0x88250f772101179a4ecfaa4b92a983676a3ce445';

function SendRbtc() {
  const { sendTransaction, state } = useSendTransaction();
  const [addressTo, setAddressTo] = useState(faucetAddress);
  const [rbtcToSend, setRbtcToSend] = useState(0.000001);

  const sendRbtc = async () => {
    const rbtcAmount = utils.parseEther(rbtcToSend.toString());
    const address = utils.getAddress(addressTo);
    await sendTransaction({ to: address, value: rbtcAmount });
  };
  return (
    <div className="send-rbtc">
      <label>
        Send
        <input
          type="number"
          value={rbtcToSend}
          onChange={(e) => setRbtcToSend(e.target.value)}
          min={0}
          step={0.001}
        />
        RBTC
      </label>
      <label>
        to address
        <input
          type="text"
          value={addressTo}
          onChange={(e) => setAddressTo(e.target.value)}
        />
      </label>
      {state.status === 'Mining' && (
        <p>Mining transaction {state.transaction.hash}</p>
      )}
      <button type="button" onClick={sendRbtc}>
        Send transaction
      </button>
    </div>
  );
}

export default SendRbtc;
